<?php

namespace Modules\Helpdesk\Http\Controllers\Managers\Settings;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;
use Modules\Helpdesk\Models\ConversationTag;

class TagsController extends Controller
{
    public function __construct()
    {
        $this->middleware('can:helpdesk.tags.view')->only(['index', 'create', 'edit']);
        $this->middleware('can:helpdesk.tags.create')->only(['store']);
        $this->middleware('can:helpdesk.tags.update')->only(['update']);
        $this->middleware('can:helpdesk.tags.delete')->only(['destroy']);
    }

    /**
     * Display a listing of tags.
     */
    public function index(Request $request)
    {
        $query = ConversationTag::query();

        // Search filter
        if ($request->filled('search')) {
            $query->search($request->search);
        }

        // Active/Inactive filter
        if ($request->filled('status')) {
            if ($request->status === 'active') {
                $query->active();
            } elseif ($request->status === 'inactive') {
                $query->where('is_active', false);
            }
        }

        $tags = $query->latest()->paginate(20);

        // Calculate statistics
        $row = ConversationTag::query()->selectRaw('
            COUNT(*) as total,
            SUM(CASE WHEN is_active = 1 THEN 1 ELSE 0 END) as active,
            SUM(CASE WHEN is_active = 0 THEN 1 ELSE 0 END) as inactive
        ')->first();

        $stats = [
            'total' => (int) $row->total,
            'active' => (int) $row->active,
            'inactive' => (int) $row->inactive,
        ];

        return view('helpdesk::settings.tags.index', [
            'tags' => $tags,
            'stats' => $stats,
        ]);
    }

    /**
     * Show the form for creating a new tag.
     */
    public function create()
    {
        return view('helpdesk::settings.tags.create');
    }

    /**
     * Store a newly created tag.
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
            'name' => 'required|string|max:255',
            'slug' => 'nullable|string|max:255|unique:helpdesk.helpdesk_conversation_tags,slug|regex:/^[a-z0-9_-]+$/',
            'color' => 'nullable|string|regex:/^#[0-9a-fA-F]{6}$/',
            'description' => 'nullable|string|max:1000',
            'is_active' => 'nullable|boolean',
        ], [
            'name.required' => 'El nombre es obligatorio.',
            'name.max' => 'El nombre no puede exceder 255 caracteres.',
            'slug.regex' => 'El slug solo puede contener letras minúsculas, números, guiones y guiones bajos.',
            'slug.unique' => 'Ya existe un tag con este slug.',
            'color.regex' => 'El color debe ser un código hexadecimal válido (#RRGGBB).',
        ]);

        // If slug is empty, it will be auto-generated by the model
        if (empty($validated['slug'])) {
            unset($validated['slug']);
        }

        $validated['is_active'] = $request->boolean('is_active', true);

        ConversationTag::create($validated);

        return redirect()->route('settings.helpdesk.tags.index')
            ->with('success', 'Tag creado exitosamente.');
    }

    /**
     * Show the form for editing a tag.
     */
    public function edit(ConversationTag $tag)
    {
        return view('helpdesk::settings.tags.edit', compact('tag'));
    }

    /**
     * Update the specified tag.
     */
    public function update(Request $request, ConversationTag $tag)
    {
        $validated = $request->validate([
            'name' => 'required|string|max:255',
            'slug' => [
                'nullable',
                'string',
                'max:255',
                'regex:/^[a-z0-9_-]+$/',
                Rule::unique('helpdesk.helpdesk_conversation_tags', 'slug')->ignore($tag->id),
            ],
            'color' => 'nullable|string|regex:/^#[0-9a-fA-F]{6}$/',
            'description' => 'nullable|string|max:1000',
            'is_active' => 'nullable|boolean',
        ], [
            'name.required' => 'El nombre es obligatorio.',
            'name.max' => 'El nombre no puede exceder 255 caracteres.',
            'slug.regex' => 'El slug solo puede contener letras minúsculas, números, guiones y guiones bajos.',
            'slug.unique' => 'Ya existe un tag con este slug.',
            'color.regex' => 'El color debe ser un código hexadecimal válido (#RRGGBB).',
        ]);

        // If slug is empty, it will be auto-generated by the model
        if (empty($validated['slug'])) {
            unset($validated['slug']);
        }

        $validated['is_active'] = $request->boolean('is_active');

        $tag->update($validated);

        return redirect()->route('settings.helpdesk.tags.index')
            ->with('success', 'Tag actualizado exitosamente.');
    }

    /**
     * Remove the specified tag.
     */
    public function destroy(ConversationTag $tag)
    {
        // Check if tag is in use
        $usageCount = $tag->conversations()->count();

        if ($usageCount > 0) {
            return redirect()->route('settings.helpdesk.tags.index')
                ->with('error', "No se puede eliminar el tag porque está siendo usado en {$usageCount} conversación(es).");
        }

        $tag->delete();

        return redirect()->route('settings.helpdesk.tags.index')
            ->with('success', 'Tag eliminado exitosamente.');
    }
}
