<?php

namespace Modules\Helpdesk\Http\Controllers\Managers\Settings;

use App\Http\Controllers\Controller;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Modules\Helpdesk\Http\Requests\StoreConversationTagRequest;
use Modules\Helpdesk\Http\Requests\UpdateConversationTagRequest;
use Modules\Helpdesk\Models\ConversationTag;

class TagsController extends Controller
{
    public function __construct()
    {
        $this->middleware('can:helpdesk.tags.view')->only(['index', 'create', 'edit']);
        $this->middleware('can:helpdesk.tags.create')->only(['store']);
        $this->middleware('can:helpdesk.tags.update')->only(['update']);
        $this->middleware('can:helpdesk.tags.delete')->only(['destroy', 'bulkAction']);
    }

    /**
     * Display a listing of tags.
     */
    public function index(Request $request)
    {
        $query = ConversationTag::query();

        // Search filter
        if ($request->filled('search')) {
            $query->search($request->search);
        }

        // Active/Inactive filter
        if ($request->filled('status')) {
            if ($request->status === 'active') {
                $query->active();
            } elseif ($request->status === 'inactive') {
                $query->where('is_active', false);
            }
        }

        $tags = $query->latest()->paginate(20);

        // Calculate statistics
        $row = ConversationTag::query()->selectRaw('
            COUNT(*) as total,
            SUM(CASE WHEN is_active = 1 THEN 1 ELSE 0 END) as active,
            SUM(CASE WHEN is_active = 0 THEN 1 ELSE 0 END) as inactive
        ')->first();

        $stats = [
            'total' => (int) $row->total,
            'active' => (int) $row->active,
            'inactive' => (int) $row->inactive,
        ];

        return view('helpdesk::settings.tags.index', [
            'tags' => $tags,
            'stats' => $stats,
        ]);
    }

    /**
     * Show the form for creating a new tag.
     */
    public function create()
    {
        return view('helpdesk::settings.tags.create');
    }

    /**
     * Store a newly created tag.
     */
    public function store(StoreConversationTagRequest $request)
    {
        $validated = $request->validated();

        // If slug is empty, it will be auto-generated by the model
        if (empty($validated['slug'])) {
            unset($validated['slug']);
        }

        $validated['is_active'] = $request->boolean('is_active', true);

        $tag = ConversationTag::create($validated);

        if ($request->wantsJson()) {
            return response()->json(['success' => true, 'tag' => ['id' => $tag->id, 'name' => $tag->name, 'color' => $tag->color]]);
        }

        return redirect()->route('settings.helpdesk.tags.index')
            ->with('success', 'Tag creado exitosamente.');
    }

    /**
     * Show the form for editing a tag.
     */
    public function edit(ConversationTag $tag)
    {
        return view('helpdesk::settings.tags.edit', compact('tag'));
    }

    /**
     * Update the specified tag.
     */
    public function update(UpdateConversationTagRequest $request, ConversationTag $tag)
    {
        $validated = $request->validated();

        // If slug is empty, it will be auto-generated by the model
        if (empty($validated['slug'])) {
            unset($validated['slug']);
        }

        $validated['is_active'] = $request->boolean('is_active');

        $tag->update($validated);

        return redirect()->route('settings.helpdesk.tags.index')
            ->with('success', 'Tag actualizado exitosamente.');
    }

    /**
     * Remove the specified tag.
     */
    public function destroy(ConversationTag $tag)
    {
        // Check if tag is in use
        $usageCount = $tag->conversations()->count();

        if ($usageCount > 0) {
            return redirect()->route('settings.helpdesk.tags.index')
                ->with('error', "No se puede eliminar el tag porque está siendo usado en {$usageCount} conversación(es).");
        }

        $tag->delete();

        return redirect()->route('settings.helpdesk.tags.index')
            ->with('success', 'Tag eliminado exitosamente.');
    }

    /**
     * Apply a bulk action (activate, deactivate, delete) to the selected tags.
     * Delete respects the same in-use protection as destroy(): tags linked to
     * conversations are skipped rather than deleted.
     */
    public function bulkAction(Request $request): JsonResponse
    {
        $validated = $request->validate([
            'action' => ['required', 'string', 'in:activate,deactivate,delete'],
            'ids' => ['required', 'array', 'min:1'],
            'ids.*' => ['integer'],
        ]);

        $tags = ConversationTag::whereIn('id', $validated['ids'])->get();
        $count = 0;
        $skipped = 0;

        if ($validated['action'] === 'delete') {
            foreach ($tags as $tag) {
                if ($tag->conversations()->count() > 0) {
                    $skipped++;

                    continue;
                }

                $tag->delete();
                $count++;
            }
        } else {
            foreach ($tags as $tag) {
                $tag->update(['is_active' => $validated['action'] === 'activate']);
                $count++;
            }
        }

        $labels = [
            'delete' => 'eliminado(s)',
            'activate' => 'activado(s)',
            'deactivate' => 'desactivado(s)',
        ];

        $message = "{$count} etiqueta(s) {$labels[$validated['action']]}.";

        if ($skipped > 0) {
            $message .= " {$skipped} omitida(s) por estar en uso.";
        }

        return response()->json([
            'message' => $message,
            'count' => $count,
            'skipped' => $skipped,
        ]);
    }
}
