// Data for conversations prototype
const AGENTS = [
  { id: 1, name: 'María López', initials: 'ML', color: 'c2', online: 'on', role: 'Soporte N1' },
  { id: 2, name: 'Carlos Ruiz', initials: 'CR', color: 'c5', online: 'on', role: 'Soporte N2' },
  { id: 3, name: 'Ana Torres', initials: 'AT', color: 'c3', online: 'away', role: 'Ventas' },
  { id: 4, name: 'Diego Vega', initials: 'DV', color: 'c4', online: 'off', role: 'Soporte N1' },
  { id: 5, name: 'Laura Soto', initials: 'LS', color: 'c1', online: 'on', role: 'Supervisora' },
];

const TAGS = [
  { id:'fac', label:'Facturación', color:'#f59e0b' },
  { id:'env', label:'Envío', color:'#3b82f6' },
  { id:'dev', label:'Devolución', color:'#ef4444' },
  { id:'vip', label:'VIP', color:'#8b5cf6' },
  { id:'esp', label:'Esperando cliente', color:'#a1a1aa' },
  { id:'ur', label:'Urgente', color:'#dc2626' },
];

const CANNED = [
  { sh:'/gracias', t:'Agradecimiento', p:'¡Gracias por contactarnos! En breve un agente revisará tu solicitud.' },
  { sh:'/estado', t:'Pedido — estado', p:'Déjanos tu número de pedido (empieza por #) y revisamos el estado ahora mismo.' },
  { sh:'/horario', t:'Horario de atención', p:'Nuestro horario es L-V 9:00-18:00. Te responderemos en el siguiente turno.' },
  { sh:'/envio', t:'Info de envío', p:'El plazo estándar es 24-48h. Recibirás el tracking por email cuando salga del almacén.' },
  { sh:'/dev', t:'Política de devolución', p:'Puedes devolver tu pedido en 30 días. Adjunto el enlace al formulario: https://…' },
  { sh:'/cierre', t:'Cierre de ticket', p:'Si todo está resuelto, cierro el ticket. ¡Escríbenos si necesitas algo más!' },
];

const CONVERSATIONS = [
  {
    id: 1, channel:'whatsapp', ch_label:'WhatsApp',
    contact:'Julia García', phone:'+34 612 345 678', email:'julia.g@gmail.com', company:'Particular',
    initials:'JG', color:'c1',
    preview:'Hola, el pedido #8421 no ha llegado y debería haber…',
    time:'2 min', unread:3, urgency:'urgent',
    sla:{ label:'04:12', state:'warn' },
    assignee:1, status:'open', priority:'urgent',
    tags:['ur','env'],
    group:'Hoy',
    typing:true,
  },
  {
    id: 2, channel:'instagram', ch_label:'Instagram',
    contact:'@marcos.diaz', phone:null, email:null, company:'Marcos Díaz',
    initials:'MD', color:'c4',
    preview:'Tú: Perfecto, ya te hemos enviado el enlace de pago',
    time:'8 min', unread:0, urgency:null,
    sla:{ label:'12:44', state:'ok' },
    assignee:2, status:'pending', priority:'normal',
    tags:['fac'],
    group:'Hoy',
    out:true,
  },
  {
    id: 3, channel:'facebook', ch_label:'Facebook',
    contact:'Sandra Peña', phone:null, email:'sandra@empresa.com', company:'Ecom Ibérica',
    initials:'SP', color:'c3',
    preview:'📎 cotizacion-2026.pdf · Por favor, revisen…',
    time:'23 min', unread:1, urgency:'high',
    sla:{ label:'01:08', state:'warn' },
    assignee:1, status:'open', priority:'high',
    tags:['fac','vip'],
    group:'Hoy',
  },
  {
    id: 4, channel:'widget', ch_label:'Web widget',
    contact:'Alex Moreno', phone:null, email:'alex@hotmail.es', company:'Particular',
    initials:'AM', color:'c5',
    preview:'🎤 Nota de voz · 0:34',
    time:'48 min', unread:2, urgency:null,
    sla:{ label:'00:18', state:'breach' },
    assignee:null, status:'open', priority:'urgent',
    tags:['dev'],
    group:'Hoy',
  },
  {
    id: 5, channel:'whatsapp', ch_label:'WhatsApp',
    contact:'Rafa Bravo', phone:'+34 611 222 333', email:null, company:'Bravo & Co.',
    initials:'RB', color:'c2',
    preview:'👍',
    time:'1 h', unread:0, urgency:null,
    sla:null,
    assignee:3, status:'open', priority:'low',
    tags:['vip'],
    group:'Hoy',
  },
  {
    id: 6, channel:'facebook', ch_label:'Facebook',
    contact:'Patricia Lima', phone:null, email:null, company:null,
    initials:'PL', color:'c6',
    preview:'¿Tienen stock del modelo azul talla M?',
    time:'2 h', unread:1, urgency:null,
    sla:null,
    assignee:2, status:'open', priority:'normal',
    tags:[],
    group:'Hoy',
  },
  {
    id: 7, channel:'whatsapp', ch_label:'WhatsApp',
    contact:'Mario Fernández', phone:'+34 699 888 777', email:'mario.f@yahoo.es',
    initials:'MF', color:'c1',
    preview:'Tú: Te adjunto la factura rectificativa',
    time:'Ayer', unread:0, urgency:null,
    sla:null,
    assignee:1, status:'pending', priority:'normal',
    tags:['fac','esp'],
    group:'Ayer',
    out:true,
  },
  {
    id: 8, channel:'instagram', ch_label:'Instagram',
    contact:'@leo.runs', phone:null, email:null, company:'Leo Vargas',
    initials:'LV', color:'c3',
    preview:'Mil gracias por la ayuda 🙌',
    time:'Ayer', unread:0, urgency:null,
    sla:null,
    assignee:2, status:'closed', priority:'low',
    tags:[],
    group:'Ayer',
  },
  {
    id: 9, channel:'widget', ch_label:'Web widget',
    contact:'Natalia R.', phone:null, email:'nataliar@corp.com', company:'Corp Digital SL',
    initials:'NR', color:'c4',
    preview:'Recibido, muchas gracias',
    time:'Ayer', unread:0, urgency:null,
    sla:null,
    assignee:4, status:'closed', priority:'normal',
    tags:['vip'],
    group:'Ayer',
  },
  {
    id: 10, channel:'whatsapp', ch_label:'WhatsApp',
    contact:'Elena Soler', phone:'+34 644 111 000', email:null,
    initials:'ES', color:'c5',
    preview:'Tú: Un placer, Elena. Que tengas un buen día',
    time:'Lun', unread:0, urgency:null,
    sla:null,
    assignee:1, status:'closed', priority:'normal',
    tags:[],
    group:'Esta semana',
    out:true,
  },
  {
    id: 11, channel:'facebook', ch_label:'Facebook',
    contact:'Iván Prieto', phone:null, email:null, company:null,
    initials:'IP', color:'c2',
    preview:'Ok perfecto, gracias!',
    time:'Lun', unread:0, urgency:null,
    sla:null,
    assignee:3, status:'closed', priority:'low',
    tags:[],
    group:'Esta semana',
  },
];

const MESSAGES_J1 = [
  { t:'day', label:'Hoy' },
  {
    id:'m1', dir:'in', author:'Julia García', ai:'JG', color:'c1', time:'14:02',
    body:'Hola! Hice un pedido hace ya 5 días y aún no ha llegado. El número es #8421.',
  },
  {
    id:'m2', dir:'in', author:'Julia García', ai:'JG', color:'c1', time:'14:02',
    attachments:[{ type:'image', c1:'#fecaca', c2:'#fde68a', name:'foto_caja.jpg', size:'1.2 MB' }],
  },
  {
    id:'m3', dir:'out', author:'María López', ai:'ML', color:'c2', time:'14:05', read:true,
    body:'Hola Julia, gracias por contactarnos. Entiendo tu preocupación — déjame revisar el estado del pedido #8421.',
  },
  { t:'event', ico:'fa-tag', body:'<b>María López</b> añadió la etiqueta <b>Envío</b>', time:'14:05' },
  { t:'event', ico:'fa-user-check', body:'Asignada a <b>María López</b>', time:'14:05' },
  {
    id:'m4', dir:'out', internal:true, author:'María López', ai:'ML', color:'c2', time:'14:07',
    body:'Chicos, veo que el transportista marcó "incidencia" pero no hay más detalles. @carlos ¿puedes echar un vistazo al sistema de envíos? Es VIP repetido.',
  },
  {
    id:'m5', dir:'out', internal:true, author:'Carlos Ruiz', ai:'CR', color:'c5', time:'14:09',
    body:'Visto. Hay un error de dirección — la calle viene sin número. Le pido que confirme y reenvío el mismo día.',
    reactions:[{ e:'👍', c:2, mine:true }],
  },
  {
    id:'m6', dir:'out', author:'María López', ai:'ML', color:'c2', time:'14:11', read:true,
    replyTo:{ who:'Julia García', text:'Hice un pedido hace ya 5 días y aún no ha llegado…' },
    body:'Julia, hemos detectado una incidencia con la dirección: nos falta el número del portal. ¿Puedes confirmarnos la dirección completa? Reenviamos hoy mismo sin coste.',
  },
  {
    id:'m7', dir:'in', author:'Julia García', ai:'JG', color:'c1', time:'14:13',
    body:'Claro! Es Calle Mayor 42, 3º B, 28013 Madrid. Muchas gracias por gestionarlo tan rápido 🙏',
    reactions:[{ e:'❤️', c:1 }],
    translation:{ from:'es', txt:'Sure! It\'s Calle Mayor 42, 3rd floor B, 28013 Madrid. Thank you so much for handling it so quickly 🙏' },
  },
  {
    id:'m8', dir:'in', author:'Julia García', ai:'JG', color:'c1', time:'14:14',
    attachments:[{ type:'audio', duration:'0:21' }],
  },
  {
    id:'m9', dir:'in', author:'Julia García', ai:'JG', color:'c1', time:'14:18',
    body:'Y ya que estamos, ¿puedes confirmarme si el envío incluye el regalo que vi en la promo?',
  },
];

const KEYMAP = [
  { sec:'Navegación', rows:[
    { lbl:'Conversación siguiente', keys:['J'] },
    { lbl:'Conversación anterior', keys:['K'] },
    { lbl:'Buscar conversaciones', keys:['⌘','F'] },
    { lbl:'Ir a bandeja', keys:['G','I'] },
    { lbl:'Ir a menciones', keys:['G','M'] },
    { lbl:'Alternar panel derecho', keys:['⌘','.'] },
  ]},
  { sec:'Acciones en conversación', rows:[
    { lbl:'Responder', keys:['R'] },
    { lbl:'Nota interna', keys:['N'] },
    { lbl:'Asignar agente', keys:['A'] },
    { lbl:'Etiquetar', keys:['T'] },
    { lbl:'Cerrar', keys:['E'] },
    { lbl:'Archivar', keys:['⇧','E'] },
    { lbl:'Snooze', keys:['Z'] },
  ]},
  { sec:'Composer', rows:[
    { lbl:'Enviar', keys:['⌘','↵'] },
    { lbl:'Respuestas rápidas', keys:['/'] },
    { lbl:'Sugerencia IA', keys:['⌘','J'] },
    { lbl:'Mencionar equipo', keys:['@'] },
    { lbl:'Adjuntar archivo', keys:['⌘','⇧','A'] },
  ]},
  { sec:'General', rows:[
    { lbl:'Paleta de comandos', keys:['⌘','K'] },
    { lbl:'Atajos de teclado', keys:['?'] },
    { lbl:'Tema claro/oscuro', keys:['⌘','⇧','T'] },
  ]},
];

window.CONV_DATA = { AGENTS, TAGS, CANNED, CONVERSATIONS, MESSAGES_J1, KEYMAP };
