[program:laravel-scheduler]
process_name=%(program_name)s
command=/bin/bash /var/www/deployment/scripts/scheduler.sh
autostart=true
autorestart=true
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/storage/logs/supervisor/scheduler.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=10
user=www-data
startsecs=10
stopwaitsecs=10
priority=999
