[program:alsernet-comparador]
process_name=%(program_name)s
command=/bin/bash -c "while true; do /usr/bin/php /home/comparador/web/artisan schedule:run --quiet; sleep 60; done"
directory=/home/comparador/web
autostart=true
autorestart=true
user=www-data
numprocs=1
redirect_stderr=true

stdout_logfile=/home/comparador/web/storage/logs/scheduler.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=10

startsecs=5
startretries=10
stopsignal=TERM
stopwaitsecs=60
stopasgroup=true
killasgroup=true
